using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using PubFuncWt;
using goa.Common;

namespace MountSiteDesignAnaly
{
    internal class Hide : RequestMethod
    {
        internal Hide(UIApplication _uiApp) : base(_uiApp)
        {

        }

        internal override void Execute()
        {

            List<ElementFilter> elementFilters =
                new List<ElementFilter>()
                {
                    new ElementCategoryFilter(BuiltInCategory.OST_AreaTags),
                    new ElementCategoryFilter(BuiltInCategory.OST_AreaSchemeLines),
                    new ElementCategoryFilter(BuiltInCategory.OST_Areas)
                };

            LogicalOrFilter logicalOrFilter = new LogicalOrFilter(elementFilters);

            ICollection<ElementId> elements = (new FilteredElementCollector(this.doc)).WherePasses(logicalOrFilter).WhereElementIsNotElementType().ToElementIds();

            List<ElementId> elementIds = new List<ElementId>();
            foreach (var eleId in elements)
            {
                Element element = this.doc.GetElement(eleId);

                if (element is AreaTag)
                {
                    if (element.Name.Contains("EarthworkInfor"))
                    {
                        elementIds.Add(eleId);
                    }
                }
                else
                {
                    elementIds.Add(eleId);
                }
            }

            AutoGeneratedElementMgr autoGeneratedElementMgr = new AutoGeneratedElementMgr(this.doc, this.AreaShowHideInfo);

            using (Transaction trans = new Transaction(this.doc, "隐藏面积图元及其标记信息"))
            {
                trans.Start();
                autoGeneratedElementMgr.SaveIds(elementIds.Select(p => p.IntegerValue.ToString()));
                this.view.HideElements(elementIds);
                trans.Commit();
            }

            //throw new NotImplementedException();
        }
    }
}
