using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using PubFuncWt;
using goa.Common;

namespace MountSiteDesignAnaly
{
    internal class Show : RequestMethod
    {
        internal Show(UIApplication _uiApp) : base(_uiApp)
        {

        }

        internal override void Execute()
        {
            AutoGeneratedElementMgr autoGeneratedElementMgr = new AutoGeneratedElementMgr(this.doc, this.AreaShowHideInfo);

            List<ElementId> eleIds = new List<ElementId>();

            foreach (var item in autoGeneratedElementMgr.ReadIds())
            {
                int result;
                int.TryParse(item, out result);

                Element element = this.doc.GetElement(new ElementId(result));

                if (!ReferenceEquals(element, null) && element.IsValidObject)
                {
                    eleIds.Add(new ElementId(result));
                }
            }

            using (Transaction trans = new Transaction(this.doc, "隐藏面积图元及其标记信息"))
            {
                if (eleIds.Count > 0)
                {
                    trans.Start();
                    this.view.UnhideElements(eleIds);
                    trans.Commit();
                }
            }

            //throw new NotImplementedException();
        }
    }
}
