using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Autodesk.Revit.DB;

namespace PubFuncWt
{

    public static class Precision_
    {

        #region Math

        /// <summary>
        /// 判断两个数据是否相等，计算机计算会产生不可避免的误差 1e-5
        /// </summary>
        public static double Precison { get { return 1e-5; } }// 0.001 foot * 304.8 = 0.3048 mm）
        /// <summary>
        /// Revit中创建实体线的最短线段距离（the shortest distance 0.00256026455729167 foot * 304.8 = 0.7803686370624797 mm） 3e-3 约等于0.8mm
        /// </summary>
        public static double TheShortestDistance { get { return 3e-3; } }
        /// <summary>
        /// 这里给出角度容差值，源于，图形处理结果会发生尖角的情况 1e-1
        /// </summary>
        public static double AnglePRECISION { get { return 1e-1; } }
        /// <summary>
        /// 重合的点，在坐标值放大的情况下，会造成出现距离影响clipper计算，Clipper接受大到±4.6e18的整数坐标，Revit接受的最大线段长度 9144000mm = 9.144km / 304.8 = +3e4f oot
        /// </summary>
        public static double ClipperMultiple { get { return 1e14; } }
        /// <summary>
        /// 由于Revit数据读入代码后会缩小为自身304.8的倍，这里手动放大，保证代码的数字1是1mm的世界尺度，代码手动放大，记得手动缩小回去
        /// </summary>
        public static double RevitSizeUnitMagFactor { get { return 304.7999995367; } }
        /// <summary>
        /// 单次绘制最长长度-mm
        /// </summary>
        public static double LongestSingleDraw_mm { get { return 9144000.0; } }
        /// <summary>
        /// 单次绘制最长长度-feet
        /// </summary>
        public static double LongestSingleDraw_feet { get { return 30000.00000984252; } }

        public static XYZ ShortestXYZ { get { return new XYZ(TheShortestDistance, TheShortestDistance, TheShortestDistance); } }
        #endregion

        #region Guid
        //public static Guid Guid_AutoGeneratedElementMgrSchema = new Guid("4d0ebcfe-7603-466e-9369-6298de31dd47");

        //public static Guid Guid_ElementListOfId = new Guid("3b5485ae-e02d-49ac-b7fb-72a001085b96");
        #endregion
    }
}
