using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Autodesk.Revit.DB.ExtensibleStorage;

namespace goa.Common
{
    public static partial class SchemaTypes
    {
        public static Schema DocumentId;
        public static Guid Guid_DocumentId = new Guid("AC621CB2-BCB4-4C7C-8C2D-21A9FEED5245");

        public static Schema AutoGeneratedElementMgrSchema;
        public static Guid Guid_AutoGeneratedElementMgrSchema = new Guid("4d0ebcfe-7603-466e-9369-6298de31dd47");

        public static Schema ElementListOfId;
        public static Guid Guid_ElementListOfId = new Guid("3b5485ae-e02d-49ac-b7fb-72a001085b96");

        public static bool Initialized = false;

        public static void InitializeTypes()
        {
            if (!Initialized)
            {
                DocumentId = Schema.Lookup(Guid_DocumentId);
                if (DocumentId == null)
                    DocumentId = Create_DocumentId();
                ElementListOfId = Schema.Lookup(Guid_ElementListOfId);
                if (ElementListOfId == null)
                    ElementListOfId = create_ElementListOfId();
                AutoGeneratedElementMgrSchema = Schema.Lookup(Guid_AutoGeneratedElementMgrSchema);
                if (AutoGeneratedElementMgrSchema == null)
                    AutoGeneratedElementMgrSchema = create_AutoGeneratedElementMgrSchema();
                Initialized = true;
            }
        }
        private static Schema create_AutoGeneratedElementMgrSchema()
        {
            SchemaBuilder sb = new SchemaBuilder(Guid_AutoGeneratedElementMgrSchema);
            sb.SetSchemaName("AutoGeneratedElementMgrSchema");
            sb.SetReadAccessLevel(AccessLevel.Public);
            FieldBuilder fb1 = sb.AddMapField("ElementListOfId", typeof(string), typeof(Entity)); //addin_id / element_list_entity
            fb1.SetSubSchemaGUID(Guid_ElementListOfId);

            Schema sm = sb.Finish();
            return sm;
        }

        private static Schema create_ElementListOfId()
        {
            SchemaBuilder sb = new SchemaBuilder(Guid_ElementListOfId);
            sb.SetSchemaName("ElementListOfId");
            sb.SetReadAccessLevel(AccessLevel.Public);
            FieldBuilder fb1 = sb.AddArrayField("ElementList", typeof(string)); //element unique ids

            Schema sm = sb.Finish();
            return sm;
        }

        private static Schema Create_DocumentId()
        {
            SchemaBuilder sb = new SchemaBuilder(Guid_DocumentId);
            sb.SetSchemaName("DocumentId");
            sb.SetReadAccessLevel(AccessLevel.Public); //any reading atempt must start from main process, not directly from Modeless form.
            sb.AddSimpleField("GUID", typeof(Guid));

            Schema sm = sb.Finish();
            return sm;
        }
    }
}
